#Niphattha (Pat) Wongwiset
#nw9ca@virginia.edu
#Makefile
#11/16/17

CXX=clang $(CXXFLAGS)
CXXFLAGS=-Wall 
OFILES= linkedlist.o
.SUFFIXES: .o .c
wordPuzzle: $(OFILES)
	$(CXX) $(OFILES)
clean:
	-rm -f *.o *~

